export const OPEN_UNSAVED_CHANGES_MODAL =
  'app/confirmationModal/OPEN_UNSAVED_CHANGES_MODAL';

export const ACCEPT_UNSAVED_CHANGES_MODAL =
  'app/confirmationModal/ACCEPT_UNSAVED_CHANGES_MODAL';

export const DISCARD_UNSAVED_CHANGES_MODAL =
  'app/confirmationModal/DISCARD_UNSAVED_CHANGES_MODAL';

export const CANCEL_UNSAVED_CHANGES_MODAL =
  'app/confirmationModal/CANCEL_UNSAVED_CHANGES_MODAL';
